# Generated by Django 5.0.2 on 2024-02-22 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tools',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('toolName', models.CharField(max_length=200)),
                ('toolLink', models.CharField(max_length=200)),
                ('toolDescription', models.CharField(max_length=500)),
                ('classT', models.CharField(max_length=200)),
                ('cat', models.CharField(max_length=200)),
                ('term', models.CharField(max_length=200)),
                ('subject', models.CharField(max_length=200)),
                ('date', models.DateField(auto_now=True)),
            ],
        ),
    ]
