# Generated by Django 5.0.2 on 2024-02-27 09:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseApp', '0002_tools'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activityName', models.CharField(max_length=200)),
                ('time', models.TimeField()),
                ('teacherActivity', models.CharField(max_length=1500)),
                ('studentActivity', models.CharField(max_length=1500)),
                ('notes', models.CharField(max_length=1500)),
                ('date_created', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sessionName', models.CharField(max_length=200)),
                ('dateCreated', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topicName', models.CharField(max_length=200)),
                ('dateCreated', models.DateField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Tools',
        ),
        migrations.AddField(
            model_name='activity',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baseApp.session'),
        ),
        migrations.AddField(
            model_name='session',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baseApp.topic'),
        ),
    ]
