# Generated by Django 5.0.2 on 2024-02-27 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseApp', '0003_activity_session_topic_delete_tools_activity_session_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='notes',
            field=models.CharField(blank=True, max_length=1500, null=True),
        ),
    ]
