# Generated by Django 4.2.10 on 2024-03-27 06:54

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('baseApp', '0005_fundiuser_classtaught_fundiuser_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='classTaught',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='topic',
            name='subject',
            field=models.CharField(default=datetime.datetime(2024, 3, 27, 6, 54, 16, 658681, tzinfo=datetime.timezone.utc), max_length=200),
            preserve_default=False,
        ),
    ]
