# Generated by Django 4.2.10 on 2024-04-01 08:44

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baseApp', '0006_topic_classtaught_topic_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='activityName',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='studentActivity',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='teacherActivity',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='time',
        ),
        migrations.AddField(
            model_name='activity',
            name='activity_name',
            field=models.CharField(default=datetime.datetime(2024, 4, 1, 8, 44, 38, 614509, tzinfo=datetime.timezone.utc), max_length=255),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='VideoActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_or_image', models.FileField(upload_to='uploaded_videos')),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('activity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='baseApp.activity')),
            ],
        ),
        migrations.CreateModel(
            name='TextActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
                ('teacherActivity', models.CharField(max_length=1500)),
                ('studentActivity', models.CharField(max_length=1500)),
                ('notes', models.CharField(blank=True, max_length=1500, null=True)),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baseApp.activity')),
            ],
        ),
    ]
