# Generated by Django 4.2.10 on 2024-04-01 08:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseApp', '0008_alter_videoactivity_video_or_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoactivity',
            name='time',
            field=models.TimeField(default=datetime.datetime(2024, 4, 1, 8, 55, 35, 191072, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
