# Generated by Django 4.2.10 on 2024-04-11 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseApp', '0010_videoactivity_video_or_image_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textactivity',
            name='time',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='videoactivity',
            name='time',
            field=models.IntegerField(),
        ),
    ]
