# Generated by Django 4.2.10 on 2024-04-11 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseApp', '0011_alter_textactivity_time_alter_videoactivity_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textactivity',
            name='time',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='videoactivity',
            name='time',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
