# Generated by Django 4.2.10 on 2024-04-17 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseApp', '0012_alter_textactivity_time_alter_videoactivity_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='duration',
            field=models.CharField(default='60', max_length=200),
        ),
        migrations.AddField(
            model_name='session',
            name='learningObjective',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='session',
            name='topicCode',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='topic',
            name='term',
            field=models.CharField(default='Term I', max_length=200),
        ),
        migrations.AddField(
            model_name='topic',
            name='topicCode',
            field=models.CharField(default='', max_length=200),
        ),
    ]
