# Generated by Django 4.2.10 on 2024-04-17 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseApp', '0013_session_duration_session_learningobjective_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='cat',
            field=models.CharField(default='', max_length=200),
        ),
    ]
