# Generated by Django 4.2.10 on 2024-04-17 12:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baseApp', '0014_topic_cat'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='practicalResources',
            field=models.CharField(default='', max_length=1500),
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(default='Term I', max_length=200)),
                ('cat', models.CharField(default='', max_length=200)),
                ('subject', models.CharField(max_length=200)),
                ('classTaught', models.CharField(max_length=200)),
                ('feedback', models.CharField(max_length=1000)),
                ('dateCreated', models.DateField(auto_now=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_feedback', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
