# Generated by Django 4.2.10 on 2024-04-17 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseApp', '0015_session_practicalresources_feedback'),
    ]

    operations = [
        migrations.RenameField(
            model_name='session',
            old_name='practicalResources',
            new_name='fundibotsResources',
        ),
        migrations.AddField(
            model_name='session',
            name='schoolResources',
            field=models.CharField(default='', max_length=1500),
        ),
    ]
