# Generated by Django 4.2.10 on 2024-04-17 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baseApp', '0016_rename_practicalresources_session_fundibotsresources_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='topicCode',
        ),
    ]
