# Generated by Django 4.2.10 on 2024-04-25 04:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baseApp', '0018_remove_fundiuser_classtaught'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('image_title', models.CharField(max_length=1500)),
                ('time', models.IntegerField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.IntegerField(blank=True, null=True)),
                ('teacherActivity', models.CharField(max_length=1500)),
                ('studentActivity', models.CharField(max_length=1500)),
                ('notes', models.CharField(blank=True, max_length=1500, null=True)),
                ('date_created', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='videos/')),
                ('video_title', models.CharField(max_length=1500)),
                ('time', models.IntegerField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='videoactivity',
            name='activity',
        ),
        migrations.RenameField(
            model_name='activity',
            old_name='date_created',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='activity_name',
        ),
        migrations.AddField(
            model_name='activity',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='TextActivity',
        ),
        migrations.DeleteModel(
            name='VideoActivity',
        ),
        migrations.AddField(
            model_name='video',
            name='activity',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='video', to='baseApp.activity'),
        ),
        migrations.AddField(
            model_name='text',
            name='activity',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='text', to='baseApp.activity'),
        ),
        migrations.AddField(
            model_name='image',
            name='activity',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='baseApp.activity'),
        ),
    ]
