# Generated by Django 4.2.10 on 2024-04-25 05:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseApp', '0019_image_text_video_remove_videoactivity_activity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='mediaType',
            field=models.CharField(default=datetime.datetime(2024, 4, 25, 5, 51, 57, 674369, tzinfo=datetime.timezone.utc), max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='image',
            name='mediaType',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='text',
            name='mediaType',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='mediaType',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
