# Generated by Django 4.2.10 on 2024-04-25 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baseApp', '0020_activity_mediatype_image_mediatype_text_mediatype_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='mediaType',
        ),
    ]
