# Generated by Django 4.2.10 on 2024-04-25 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseApp', '0022_alter_activity_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='text',
            name='activity',
        ),
        migrations.RemoveField(
            model_name='video',
            name='activity',
        ),
        migrations.AddField(
            model_name='activity',
            name='image',
            field=models.ImageField(default='', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='activity',
            name='image_title',
            field=models.CharField(default='', max_length=1500),
        ),
        migrations.AddField(
            model_name='activity',
            name='notes',
            field=models.CharField(blank=True, default='', max_length=1500, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='studentActivity',
            field=models.CharField(default='', max_length=1500),
        ),
        migrations.AddField(
            model_name='activity',
            name='teacherActivity',
            field=models.CharField(default='', max_length=1500),
        ),
        migrations.AddField(
            model_name='activity',
            name='time',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='video',
            field=models.FileField(default='', upload_to='videos/'),
        ),
        migrations.AddField(
            model_name='activity',
            name='video_title',
            field=models.CharField(default='', max_length=1500),
        ),
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.DeleteModel(
            name='Text',
        ),
        migrations.DeleteModel(
            name='Video',
        ),
    ]
