# Generated by Django 4.2.10 on 2024-04-25 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseApp', '0024_alter_activity_image_alter_activity_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='mediaType',
            field=models.CharField(default='', max_length=1500),
        ),
    ]
