# Generated by Django 4.2.10 on 2024-06-21 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseApp', '0025_activity_mediatype'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='realVideo',
            field=models.BooleanField(default=True),
        ),
    ]
