# Generated by Django 4.2.10 on 2024-06-21 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baseApp', '0026_activity_realvideo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='realVideo',
        ),
    ]
