# Generated by Django 4.2.10 on 2024-06-21 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseApp', '0027_remove_activity_realvideo'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='videoType',
            field=models.CharField(default='', max_length=1500),
        ),
    ]
