# Generated by Django 4.2.10 on 2024-06-21 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baseApp', '0028_activity_videotype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='videoType',
            new_name='video_type',
        ),
    ]
