# Generated by Django 4.2.10 on 2024-06-21 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseApp', '0029_rename_videotype_activity_video_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='video_title',
            field=models.CharField(default='Actual Video', max_length=1500),
        ),
    ]
