# Generated by Django 4.2.10 on 2024-06-21 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseApp', '0030_alter_activity_video_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='video_title',
            field=models.CharField(default='', max_length=1500),
        ),
        migrations.AlterField(
            model_name='activity',
            name='video_type',
            field=models.CharField(default='Actual Video', max_length=1500),
        ),
    ]
