# Generated by Django 4.2.10 on 2024-06-21 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baseApp', '0031_alter_activity_video_title_alter_activity_video_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='video_type',
            new_name='real_video',
        ),
    ]
