# Generated by Django 4.2.10 on 2024-07-17 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseApp', '0032_rename_video_type_activity_real_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schoolName', models.CharField(default='', max_length=200)),
                ('teachersName', models.CharField(default='', max_length=200)),
                ('classTaught', models.CharField(default='', max_length=200)),
                ('phoneName', models.CharField(default='', max_length=200)),
            ],
        ),
    ]
