# Generated by Django 4.2.10 on 2024-08-20 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baseApp', '0033_teachers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('themeCode', models.CharField(default='', max_length=200)),
                ('term', models.CharField(default='Term I', max_length=200)),
                ('classTaught', models.CharField(default='', max_length=200)),
                ('date_created', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sub_Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('duration', models.IntegerField(blank=True, default=None, null=True)),
                ('learning_outcome', models.CharField(default='', max_length=1000)),
                ('date_created', models.DateField(auto_now=True)),
                ('theme', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subTheme_theme', to='baseApp.theme')),
            ],
        ),
        migrations.CreateModel(
            name='Chapters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('article', models.FileField(blank=True, default=None, null=True, upload_to='Articles/')),
                ('date_created', models.DateField(auto_now=True)),
                ('sub_theme', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chapter_subTheme', to='baseApp.sub_theme')),
            ],
        ),
    ]
