# Generated by Django 4.2.10 on 2025-03-08 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baseApp', '0036_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
