# Generated by Django 4.2.10 on 2025-03-08 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseApp', '0037_delete_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacherId', models.IntegerField(unique=True)),
                ('teacherName', models.CharField(default='', max_length=255)),
                ('schoolName', models.CharField(default='', max_length=255)),
                ('classStream', models.CharField(default='', max_length=255)),
                ('topicCovered', models.CharField(default='', max_length=255)),
                ('sessionCovered', models.CharField(default='', max_length=255)),
                ('frequency', models.CharField(default='', max_length=255)),
                ('easeOfUse', models.CharField(default='', max_length=255)),
                ('videoContentRatings', models.CharField(default='', max_length=500)),
                ('overallSatisfaction', models.IntegerField(blank=True, default=None, null=True)),
                ('challenges', models.CharField(default='', max_length=255)),
                ('improvements', models.CharField(default='', max_length=255)),
                ('additionalComments', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('evaluationDate', models.CharField(default='', max_length=255)),
            ],
        ),
    ]
