# Generated by Django 4.2.10 on 2025-03-09 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseApp', '0038_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='confidenceInESC',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='feedback',
            name='digitalContentUsefulnes',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='feedback',
            name='effectivenessOfIntruc',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='feedback',
            name='escVideoHelpfulness',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='feedback',
            name='escVideoPreparation',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='feedback',
            name='prepTimeSaved',
            field=models.CharField(default='', max_length=255),
        ),
    ]
