# Generated by Django 4.2.10 on 2025-03-09 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseApp', '0039_feedback_confidenceinesc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='teacherId',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
